#ifndef USER_FEEDBACK_EVS_H_
#define USER_FEEDBACK_EVS_H_

#define UF_PBC_MAILIST(PBC) \
PBC(UF_PBC_INVALID_STDIN_MID, "INVALID STDIN")

#define UF_INT_MAILIST(INT) \

#endif /*USER_FEEDBACK_EVS_H_*/
