#ifndef DATA_COLLECTOR_EVS_H_
#define DATA_COLLECTOR_EVS_H_

#define DATA_COLLECTOR_INT_MAILIST(INT) \
INT(DC_INT_VALID_DATA_MID, "VALID DATA") \
INT(DC_INT_INVALID_DATA_MID, "INVALID DATA") \
INT(DC_INT_STDIN_DATA_TIMEOUT_MID, "TIMEOUT STDIN") \
INT(DC_INT_COMPLETED_STORAGE_MID, "COMPLETED STORAGE") \
INT(DC_INT_STORAGE_ERROR_MID, "STORAGE ERROR") \
INT(DC_INT_POLL_DATA_MID, "POLL DATA") \

#define DATA_COLLECTOR_PBC_MAILIST(PBC) \
   PBC(DATA_COLLECTOR_PBC_MID, "PBC") \

#endif /*DATA_COLLECTOR_EVS_H_*/
