#ifndef IPC_THREAD_IDS_H_
#define IPC_THREAD_IDS_H_
 
#define IPC_THREAD_LIST(TASK_ID) \
TASK_ID(APP_WORKER_TID,       "APP") \
TASK_ID(DATA_REG_WORKER_TID,  "DATA REG") \
TASK_ID(DATA_POST_WORKER_TID, "DATA REG") \
TASK_ID(HID_WORKER_TID,       "HID") \

#endif /*IPC_THREAD_IDS_H_*/
